[drone]
code_path = "/tmp/codes"
deploy_dir_path = "/tmp/deploy"
image_svnc_path = "/tmp/image_sync"
src_registry = "10.67.14.10:5000"
remote_registry = "10.28.100.154:5000"

[[modules]]
module_name = "nangka"
image_name = "nscloud-nangka-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Nangka/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88261"
deploy_file_path = ["deploy/nangka_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "atsani"
image_name = "nscloud-atsani-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Atsani/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88327"
deploy_file_path = ["deploy/atsani_deploy.yaml.tmpl"]
template_dict = [{TEMPLATE_IMAGE_VERSION="34e4f0c2"}]

[[modules]]
module_name = "lan"
image_name = "nscloud-lan-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Lan/PVD-NGB-V1.0R00F000/dev/api"
svn_version = "88257"
deploy_file_path = ["deploy/lan.yml.tmpl"]
template_dict = []

[[modules]]
module_name = "jebi"
image_name = "nscloud-jebi-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Jebi/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88254"
deploy_file_path = ["deploy/jebi.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "higos"
image_name = "nscloud-higos-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Higos/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88253"
deploy_file_path = ["deploy/higos_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "bailu"
image_name = "nscloud-bailu-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Bailu/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88245"
deploy_file_path = ["deploy/bailu_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "hagibis"
image_name = "nscloud-hagibis-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Hagibis/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88238"
deploy_file_path = ["deploy/hagibis.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "dragon"
image_name = "nscloud-dragon-daemon"
prefix = "kunkka/iooa/"
svn_path = "https://192.168.5.246/svn/cloud/Talas/branches/4.0/dragon"
svn_version = "87644"
deploy_file_path = ["deploy/dragon-deployments.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "fileserver_v2"
image_name = "nscloud-fileserverv2-api"
prefix = "kunkka/"
svn_path = "https://192.168.5.246/svn/cloud/Talas/branches/4.0/fileserver_v2/api"
svn_version = "87677"
deploy_file_path = ["deploy/fileserverv2.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "tphoenix"
image_name = "nscloud-tphoenix-daemon"
prefix = "kunkka/iooa/"
svn_path = "https://192.168.5.246/svn/cloud/Talas/branches/4.0/tphoenix"
svn_version = "87640"
deploy_file_path = ["deploy/tphoenix-deployments.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "pserver"
image_name = "nscloud-pserver-daemon"
prefix = "kunkka/iooa/"
svn_path = "https://192.168.5.246/svn/nsseccloud/branches/debinstall/parserserver"
svn_version = "1089"
deploy_file_path = ["deploy/pserver-deployments.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "npaiserver"
image_name = "nscloud-npaiserver-daemon"
prefix = "kunkka/iooa/"
svn_path = "https://192.168.5.246/svn/nsseccloud/branches/debinstall/npaiserver"
svn_version = "1088"
deploy_file_path = ["deploy/nserver-deployments.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "halong"
image_name = "nscloud-halong-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Halong/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88211"
deploy_file_path = ["deploy/halong.yml.tmpl"]
template_dict = []

[[modules]]
module_name = "etau"
image_name = "nscloud-etau-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Etau/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88208"
deploy_file_path = ["deploy/etau.yml.tmpl"]
template_dict = []

[[modules]]
module_name = "mserver"
image_name = "nscloud-mserver-daemon"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Mserver/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88214"
deploy_file_path = ["deploy/mserver.yml.tmpl"]
template_dict = []

[[modules]]
module_name = "haishen"
image_name = "nscloud-haishen-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Haishen/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88192"
deploy_file_path = ["deploy/haishen_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "omais"
image_name = "nscloud-omais-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Omais/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88190"
deploy_file_path = ["deploy/omais_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "choi_wan"
image_name = "nscloud-choi_wan-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Choi_Wan/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88180"
deploy_file_path = ["deploy/choi_wan_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "meari"
image_name = "nscloud-meari-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Meari/PVD-NGB-V1.0R00F000/trunk/3rd/api"
svn_version = "88187"
deploy_file_path = ["deploy/meari_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "mangkhut"
image_name = "nscloud-mangkhut-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Mangkhut/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88184"
deploy_file_path = ["deploy/mangkhut.yml.tmpl"]
template_dict = []

[[modules]]
module_name = "krosa"
image_name = "nscloud-krosa-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Krosa/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88174"
deploy_file_path = ["deploy/krosa_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "tembin"
image_name = "nscloud-tembin-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Tembin/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88344"
deploy_file_path = ["deploy/tembin_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "noul"
image_name = "nscloud-noul-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Noul/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88165"
deploy_file_path = ["deploy/noul_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "fengshen"
image_name = "nscloud-fengshen-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Fengshen/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88159"
deploy_file_path = ["deploy/fengshen_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "hato"
image_name = "nscloud-hato-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Hato/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88026"
deploy_file_path = ["deploy/hato.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "dkron-proxy"
image_name = "nscloud-dkron-proxy-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Dkron/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "88097"
deploy_file_path = ["deploy/dkron-proxy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "melor"
image_name = "nscloud-melor-api"
prefix = "kunkka/saas/"
svn_path = "https://192.168.5.246/svn/cloud/Melor/PVD-NGB-V1.0R00F000/trunk/api"
svn_version = "87863"
deploy_file_path = ["deploy/melor_deploy.yaml.tmpl"]
template_dict = []

[[modules]]
module_name = "kunpeng"
image_name = "nscloud-kunpeng-daemon"
prefix = "kunkka/iooa/"
svn_path = "https://192.168.5.246/svn/cloud/Talas/branches/4.0/kunpeng"
svn_version = "87996"
deploy_file_path = []
template_dict = []